---
MetaArguments:
  global_seed: 1337
  log_file_path: plausibility_vaccine.log
ModelArguments:
  cache_dir: .cache
  pretrained_model_name: roberta-base
TrainingArguments:
  learning_rate: 0.0001
  num_train_epochs: 10.0
  optim: adamw_torch
  output_dir: results/albert_reduce_factor_64
  overwrite_output_dir: false
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 8
  use_cpu: false
FinetuningArguments:
  pretraining_tasks:
    verb_subject_score:
      data_args:
        task_name: verb_subject_score
        is_regression: true
        train_file: data/verb_understanding_data/selectional_association_subject/train.csv
        test_file: data/verb_understanding_data/selectional_association_subject/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    verb_object_score:
      data_args:
        task_name: verb_object_score
        is_regression: true
        train_file: data/verb_understanding_data/selectional_association_object/train.csv
        test_file: data/verb_understanding_data/selectional_association_object/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    mobility_pred:
      data_args:
        task_name: mobility_pred
        is_regression: false
        train_file: data/property_data/Mobility/train.csv
        test_file: data/property_data/Mobility/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    opacity_pred:
      data_args:
        task_name: opacity_pred
        is_regression: false
        train_file: data/property_data/Opacity/train.csv
        test_file: data/property_data/Opacity/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    phase_pred:
      data_args:
        task_name: phase_pred
        is_regression: false
        train_file: data/property_data/Phase/train.csv
        test_file: data/property_data/Phase/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    rigidity_pred:
      data_args:
        task_name: rigidity_pred
        is_regression: false
        train_file: data/property_data/Rigidity/train.csv
        test_file: data/property_data/Rigidity/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    sentience_pred:
      data_args:
        task_name: sentience_pred
        is_regression: false
        train_file: data/property_data/Sentience/train.csv
        test_file: data/property_data/Sentience/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    shape_pred:
      data_args:
        task_name: shape_pred
        is_regression: false
        train_file: data/property_data/Shape/train.csv
        test_file: data/property_data/Shape/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    size_pred:
      data_args:
        task_name: size_pred
        is_regression: false
        train_file: data/property_data/Size/train.csv
        test_file: data/property_data/Size/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    temperature_pred:
      data_args:
        task_name: temperature_pred
        is_regression: false
        train_file: data/property_data/Temperature/train.csv
        test_file: data/property_data/Temperature/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    texture_pred:
      data_args:
        task_name: texture_pred
        is_regression: false
        train_file: data/property_data/Texture/train.csv
        test_file: data/property_data/Texture/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
    weight_pred:
      data_args:
        task_name: weight_pred
        is_regression: false
        train_file: data/property_data/Weight/train.csv
        test_file: data/property_data/Weight/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=64]
  downstream_tasks: {}
