---
MetaArguments:
  global_seed: 1337
  log_file_path: plausibility_vaccine.log
ModelArguments:
  cache_dir: .cache
  pretrained_model_name: bert-base-uncased
TrainingArguments:
  learning_rate: 0.0001
  num_train_epochs: 10.0
  optim: adamw_torch
  output_dir: results/albert_reduce_factor_16
  overwrite_output_dir: false
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 8
  use_cpu: false
FinetuningArguments:
  pretraining_tasks: {}
  downstream_tasks:
    pep_plausibility_finetune_mlp_use_adapters:
      data_args:
        task_name: pep_plausibility_funetune_mlp_use_adapters
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    pep_plausibility_finetune_mlp_use_property_adapters:
      data_args:
        task_name: pep_plausibility_funetune_mlp_use_adapters
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    pep_plausibility_finetune_adapter_use_adapters:
      data_args:
        task_name: pep_plausibility_finetune_adapter_use_adapters
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    pep_plausibility_finetune_adapter_use_property_adapters:
      data_args:
        task_name: pep_plausibility_finetune_adapter_use_adapters
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    20q_plausibility_finetune_mlp_use_adapters:
      data_args:
        task_name: 20q_plausibility_finetune_mlp_use_adapters
        is_regression: false
        train_file: data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    20q_plausibility_finetune_mlp_use_property_adapters:
      data_args:
        task_name: 20q_plausibility_finetune_mlp_use_adapters
        is_regression: false
        train_file: data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    20q_plausibility_finetune_adapter_use_adapters:
      data_args:
        task_name: 20q_plausibility_finetune_adapter_use_adapters
        is_regression: false
        train_file: data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    20q_plausibility_finetune_adapter_use_property_adapters:
      data_args:
        task_name: 20q_plausibility_finetune_adapter_use_adapters
        is_regression: false
        train_file: data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    pep_plausibility_combined_finetune_mlp_use_adapters:
      data_args:
        task_name: pep_plausibility_combined_funetune_mlp_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    pep_plausibility_combined_finetune_mlp_use_property_adapters:
      data_args:
        task_name: pep_plausibility_combined_funetune_mlp_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    pep_plausibility_combined_finetune_adapter_use_adapters:
      data_args:
        task_name: pep_plausibility_combined_finetune_adapter_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    pep_plausibility_combined_finetune_adapter_use_property_adapters:
      data_args:
        task_name: pep_plausibility_combined_finetune_adapter_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    20q_plausibility_combined_finetune_mlp_use_adapters:
      data_args:
        task_name: 20q_plausibility_combined_finetune_mlp_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    20q_plausibility_combined_finetune_mlp_use_property_adapters:
      data_args:
        task_name: 20q_plausibility_combined_finetune_mlp_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: false
    20q_plausibility_combined_finetune_adapter_use_adapters:
      data_args:
        task_name: 20q_plausibility_combined_finetune_adapter_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - verb_subject_score
        - verb_object_score
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
    20q_plausibility_combined_finetune_adapter_use_property_adapters:
      data_args:
        task_name: 20q_plausibility_combined_finetune_adapter_use_adapters
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      fusion:
        - mobility_pred
        - opacity_pred
        - phase_pred
        - rigidity_pred
        - sentience_pred
        - shape_pred
        - size_pred
        - temperature_pred
        - texture_pred
        - weight_pred
      use_adapter_for_task: true
