---
MetaArguments:
  global_seed: 1337
  log_file_path: plausibility_vaccine.log
ModelArguments:
  cache_dir: .cache
  pretrained_model_name: albert-base-v2
TrainingArguments:
  learning_rate: 0.0001
  num_train_epochs: 10.0
  optim: adamw_torch
  output_dir: results/albert_reduce_factor_16
  overwrite_output_dir: false
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 8
  use_cpu: false
FinetuningArguments:
  pretraining_tasks: {}
  downstream_tasks:
    pep_plausibility_finetune_mlp_base:
      data_args:
        task_name: pep_plausibility_finetune_mlp_base
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      use_adapter_for_task: false
    pep_plausibility_finetune_adapter_base:
      data_args:
        task_name: pep_plausibility_finetune_adapter_base
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      use_adapter_for_task: true
    20q_plausibility_finetune_mlp_base:
      data_args:
        task_name: 20q_plausibility_finetune_mlp_base
        is_regression: false
        train_file: data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      use_adapter_for_task: false
    20q_plausibility_finetune_adapter_base:
      data_args:
        task_name: 20q_plausibility_finetune_adapter_base
        is_regression: false
        train_file: data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      use_adapter_for_task: true
    pep_plausibility_combined_finetune_mlp_base:
      data_args:
        task_name: pep_plausibility_combined_finetune_mlp_base
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      use_adapter_for_task: false
    pep_plausibility_combined_finetune_adapter_base:
      data_args:
        task_name: pep_plausibility_combined_finetune_adapter_base
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      use_adapter_for_task: true
    20q_plausibility_combined_finetune_mlp_base:
      data_args:
        task_name: 20q_plausibility_combined_finetune_mlp_base
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config:
      use_adapter_for_task: false
    20q_plausibility_combined_finetune_adapter_base:
      data_args:
        task_name: 20q_plausibility_combined_finetune_adapter_base
        is_regression: false
        train_file:
          - data/plausibility_data/pep_3k/valid.csv
          - data/plausibility_data/twentyquestions/valid.csv
        test_file: data/plausibility_data/twentyquestions/test.csv
        num_test_shards: 5
      adapter_args:
        adapter_config: seq_bn[reduction_factor=16]
      use_adapter_for_task: true
