---
# ModelArguments
cache_dir: "cache"
pretrained_model_name: "albert-base-v2"
use_fast_tokenizer: true

# DataTrainingArguments:
overwrite_cache: false
task_name: "plausibility"
train_file:
validation_file: "data/plausibility_data/pep_3k/valid.tsv"
test_file: "data/plausibility_data/pep_3k/test.tsv"

# TrainingArguments:
learning_rate: 5e-05
local_rank: 0
log_level: passive
num_train_epochs: 3.0
optim: adamw_torch
output_dir: "bar"
overwrite_output_dir: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
seed: 42
use_cpu: true

# AdapterArguments:
adapter_config: 'seq_bn'
load_adapter: ''
train_adapter: false
