---
MetaArguments:
  global_seed: 1337
  log_file_path: plausibility_vaccine.log
ModelArguments:
  cache_dir: .cache
  pretrained_model_name: albert-base-v2
TrainingArguments:
  learning_rate: 0.00005
  num_train_epochs: 3.0
  optim: adamw_torch
  output_dir: results
  overwrite_output_dir: false
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 8
  use_cpu: true
FinetuningArguments:
  pretraining_tasks:
    verb_subject_association:
      data_args:
        task_name: verb_subject_association
        is_regression: true
        train_file: data/verb_understanding_data/selectional_association_subject/train.csv
        test_file: data/verb_understanding_data/selectional_association_subject/test.csv
      adapter_args:
        adapter_config: seq_bn
    verb_object_association:
      data_args:
        task_name: verb_object_association
        is_regression: true
        train_file: data/verb_understanding_data/selectional_association_object/train.csv
        test_file: data/verb_understanding_data/selectional_association_object/test.csv
      adapter_args:
        adapter_config: seq_bn
  downstream_tasks:
    classification_head:
      data_args:
        task_name: plausibility
        is_regression: false
        train_file: data/plausibility_data/pep_3k/valid.csv
        test_file: data/plausibility_data/pep_3k/test.csv
      adapter_args:
        adapter_config: seq_bn
      fusion:
        - verb_subject_association
        - verb_subject_association
